Repository GlacioHack/xdem, pull requests merged in 2021-04, with the labels that each got.

#68 Local and regional hypsometric dDEM interpolation
  docs/source/comparison.rst
  docs/source/conf.py
  docs/source/coregistration.rst
  tests/test_ddem.py
  xdem/ddem.py
  xdem/demcollection.py
  xdem/volume.py
Labels: enhancement

#71 Modular `coreg.py` revision
  docs/source/coregistration.rst
  setup.py
  tests/test_coreg.py
  xdem/coreg.py
Labels: documentation, enhancement

#75 Added missing 'import numpy as np' statements to code examples
  docs/source/comparison.rst
Labels: documentation

#93 Use `xdem-data` repo for example data
  xdem/examples.py
Labels: enhancement

#91 Add elevation scale correction `Coreg` approach.
  tests/test_coreg.py
  xdem/coreg.py
Labels: enhancement

#85 Improvements to interpolation methods
  xdem/ddem.py
  xdem/spatial_tools.py
  xdem/volume.py
Labels: enhancement

#92 Fix typo which made docs fail
  docs/source/coregistration.rst
Labels: bug, documentation

#101 Improve documentation, add documentation testing, and make all examples into scripts.
  dev-requirements.txt
  docs/source/code/comparison.py
  docs/source/code/comparison_plot_local_hypsometric_interpolation.py
  docs/source/code/comparison_plot_regional_hypsometric_interpolation.py
  docs/source/code/comparison_plot_spatial_interpolation.py
  docs/source/code/comparison_print_cumulative_dh.py
  docs/source/code/coregistration.py
  docs/source/code/coregistration_plot_nuth_kaab.py
  docs/source/comparison.rst
  docs/source/conf.py
  docs/source/coregistration.rst
  tests/test_docs.py
  xdem/examples.py
  xdem/spstats.py
Labels: documentation, enhancement

#106 Fix interpolate_hypsometric_bins
  tests/test_volume.py
  xdem/volume.py
Labels: bug
