Repository GlacioHack/xdem, pull requests merged in 2021-05, with the labels that each got.

#95 Improve merge_rasters
  tests/test_spatial_tools.py
  xdem/spatial_tools.py
Labels: bug, enhancement

#104 Add hillshade function.
  tests/test_spatial_tools.py
  xdem/spatial_tools.py
Labels: enhancement

#117 Updated test syntax to work with latest geoutils
  tests/test_dem.py
Labels: enhancement

#118 Fix hypsometric interpolation for large gaps
  xdem/volume.py
Labels: bug, enhancement

#120 Update readme and environment.yml to make installation easier with conda+pip
  .github/workflows/python-package.yml
  README.md
  environment.yml
  setup.py
  tests/test_ddem.py
Labels: documentation, invalid

#131 Change URLs in accordance with geoutils master->main rename.
  environment.yml
  setup.py
Labels: enhancement

#125 Add a filter module and several filters.
  tests/test_filters.py
  xdem/__init__.py
  xdem/filters.py
Labels: enhancement
