Repository GlacioHack/xdem, pull requests merged in 2021-03, with the labels that each got.

#22 Fixed bug in setup.py and made coreg + spatial_tools tests pass
  setup.py
  tests/__init__.py
  tests/test_coreg.py
  tests/test_spatial_tools.py
Labels: bug

#27 Test for DEM class
  .gitignore
  tests/test_dem.py
  xdem/dem.py
Labels: enhancement

#28 Updated README.md with new terminology
  README.md
Labels: documentation

#34 Move examples to one place: a separate examples directory + ICP coreg improvements
  .gitignore
  environment.yml
  setup.py
  tests/test_coreg.py
  xdem/coreg.py
  xdem/examples.py
Labels: enhancement

#35 Function to merge rasters using any callable (mean, median, sum etc)
  tests/test_spatial_tools.py
  xdem/spatial_tools.py
Labels: enhancement

#37 Spatial statistics: empirical variogram estimation, numerical variogram integration into volume errors
  environment.yml
  tests/test_spstats.py
  xdem/__init__.py
  xdem/spstats.py
Labels: enhancement

#38 Fix history to remove blobs above 3 MiB
  xdem/__init__.py
Labels: enhancement

#49 Fix 'pip install' to install all dependencies
  setup.py
  xdem/coreg.py
Labels: enhancement

#36 Local hypsometric interpolation
  tests/test_volume.py
  xdem/__init__.py
  xdem/volume.py
Labels: enhancement

#63 Added barebones documentation
  .gitignore
  dev-requirements.txt
  docs/Makefile
  docs/make.bat
  docs/source/comparison.rst
  docs/source/conf.py
  docs/source/coregistration.rst
  docs/source/index.rst
  docs/source/spatial_stats.rst
  docs/source/tutorials.rst
  xdem/coreg.py
  xdem/volume.py
Labels: documentation

#42 DEMCollection and dDEM classes
  docs/source/comparison.rst
  tests/test_ddem.py
  tests/test_demcollection.py
  xdem/__init__.py
  xdem/ddem.py
  xdem/demcollection.py
  xdem/examples.py
  xdem/spatial_tools.py
Labels: enhancement
